apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ieknb98dx-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ieknb98dx-nodejs 
  name: ieknb98dx-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ieknb98dx-nodejs 
